version: '3'
services:
  password_manager:
    build: .
    working_dir: /usr/src/app
    container_name: password_manager
    volumes:
      - .:/usr/src/app
    command: python app/main.py
    stdin_open: true
    tty: true
