version: '3.8'

services:
  password_manager:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: python app/main.py
    stdin_open: true
    tty: true
