version: '3.8'

services:
  password_manager:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app           # Bind mount the project directory
      - password_data:/usr/src/app/data  # Named volume for persistence
    command: python app/main.py
    stdin_open: true
    tty: true

volumes:
  password_data:
